### ISSUE TITLE
Referring to environment variables from cjson files

### ISSUE THREAD

**Issue by msiebuhr** [One-com/node-oconf#10]
I need to use both some static-like config (regular oconf), and refer to variables exported through the local environment (ex. https://devcenter.heroku.com/articles/config-vars). However, I would like for these to be 'mixed' into the regular oconf data, for easier management/testing/...

I was thinking of looking throug our data for stuff like `/^\$(ENV_NAME)$/` or even `/^ENV:\$(ENV_NAME)$/' and replace it with local environment varialbes, if found.

Comments, ideas, stuff I missed?

**Comment by gustavnikolaj** [comment]
I'm not sure I understand the use case. Why is it necessary to have the environment variables in configuration instead of just using them directly via process.env in the application?

**Comment by msiebuhr** [comment]
When you don't control the underlying infrastructure, ex. running on Heroku (where config is either given via SCM or environment variables).

We currently pull it from `process.env`, but it's code we now have replicated a dusin or so times, so I'd rather do it in a more central manner.

**Comment by gustavnikolaj** [comment]
Okay, I see...

It's easy enough for single values, where one could imagine something like:

```json
{
  "someVariable": {"#ENV": "SOMEENVIRONMENTVARIABLE" }
}
```

But what about including those values in a list?

And what should happen if the environment variable is missing?

**Comment by msiebuhr** [comment]
Yeah. I have some of those cases a bit of though as well, but came up with no really good ideas.

We can do all sorts of things if we extend the `#inlcude`-syntax to work with environment variables, but to have it as values, I see three avenues:

Nothing: `{foo: { #ENV: NAME}}` -> `{foo: {#ENV: VALUE}}`
Drop the object: -> `{foo: VALUE}`
Use an array: `["#env", "NAME"]` -> `VALUE`.

We could also encode the environment name inside the value:`{"foo": "#ENV:NAME"}` -> `{foo: VALUE}`.

While I'm in no way happy about using the values, I think it's the most readable and delivers the best support for the current flow in oconf. Also makes it obvious what happens when run with tools that doesn't understand the #ENV rules.

**Comment by msiebuhr** [comment]
While we're on brainstorming, we could also re-use `#include` in values, ex: `#include:env:name` / `#include:file:filename`, ...

Stealing a page from Go's [encoding/json](http://godoc.org/encoding/json#Marshal) module we could also have options in there: `#env[,option]+:name`, ex `#env,failonempty:NAME`, `#env,ignoreempty:NAME`, possibly even default values.

**Comment by gustavnikolaj** [comment]
If we should choose to go with the value route, I'd vote for the { "#ENV": "ENV_VAR_NAME" } syntax. The other two are less obvious in my opinion.

The same goes for the other examples to be honest.

But I guess we could steal some of the concepts from golang anyway, and combine it with the object syntax above:

```json
{
  "foo": {
    "#ENV": "ENV_VAR_NAME",
    "failonempty|ignoreempty|omitifempty": true
  }
}
```

**Comment by gustavnikolaj** [comment]
I know it's verbose, but I prefer that to magic :-)

**Comment by msiebuhr** [comment]
Also, not WYSIWYG when passing stuff though `oconf` - the object you get out may have a quit different structure than what you put in.

I'll think it over, but for now, I strongly prefer the inline syntax over the compact-on-load. Alternately, it might be worth to write another small library to try different things out.

**Comment by gustavnikolaj** [comment]
I did not consider the argument that you want the structure to be as close as what you get out as possible. But I see your point.

But we already have a magic key "#include". I think introducing a new magic key "#env" that transformed the object to a string value of the named ENV variable is similar enough in behaviour to "#include" that it wouldn't be too surprising.

Adding the compact syntax is an entirely new concept and thus adds up to more complexity in my opinion.

**Comment by msiebuhr** [comment]
I originally wrote up oconf as a hack to avoid the whole DLS-in-JSON crap (try reading a Vows-suite you haven't touched in a year to see what I mean).

*One* magic feature (and a simple one of that) made everything else follow quite elegantly, IMHO. I daresay the quite direct mapping from oconf-file to what object you get in code is the biggest strength, and I'm very reluctant to give up on that.

**Comment by gustavnikolaj** [comment]
The problem I have with the proposed syntax `{ "foo": "#env:BAR" }` is that it is a magic value. `"#include"` is magic too, but it's the key that contains the magic and that is less surprising to me...

Just to ensure that we agree on the disagreement; you want:

```json
{
    "foo": "#env:SOME_ENV_VAR"
}
```

Where I am more in favor of:

```json
{
    "foo": {
        "#env": "SOME_ENV_VAR"
    }
}
```

Right?

I'd like to hear @papandreou's opinion on this.

**Comment by papandreou** [comment]
I assume that we trust the configuration files? If so, a lazier solution that could support many other use cases would be to allow `eval`ing a value:

```json
{
    "foo#eval": "process.env.SOME_ENV_VAR",
    "bar#eval": "require('os').hostname()"
}
```

**Comment by msiebuhr** [comment]
I think this is straying rather far from what I imagined, so I've gone the Node-way and made it a module of it's own: [env-expander](https://github.com/msiebuhr/env-expander).

Values on the form `ENV:$var_name` will be swapped for `$var_name` (and throw an error if it isn't there).
