### ISSUE TITLE
Duality between `oconf file a.b.c` and `oconf-extract-option file a.b.c`

### ISSUE THREAD

**Issue by msiebuhr** [One-com/node-oconf#14]
They more or less do the same (I wrote the latter because I didn't know the first one existed). We should pick one and make that work smoothly.

**Comment by msiebuhr** [comment]
Also, I had an idea about `oconf` supporting multiple files, as if having a top-level `#include: [file1, file2, ...]`, which can't be done in a non-breaking manner now.

**Comment by gustavnikolaj** [comment]
Thinking about it, I'd actually prefer having it as a separate tool as the one you wrote. It makes everything a lot clearer. Especially the `--allowmissing` flag to oconf is currently a bit ambiguous; I wouldn't be surprised if people who knew the code less than I would expect it to refer to included files.

**Comment by msiebuhr** [comment]
When I first saw `--allowmissing`, I assumed it would make `oconf` silently ignore `#include`-files that couldn't be found :)

:+1:

**Comment by gustavnikolaj** [comment]
I documented the changes that I believe is necessary to bring this back in line. Please add anything that I might have missed in #18. :-)
