### ISSUE TITLE
Add support to resolve multiple configuration files from the oconf binary

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/node-oconf#19]
As @msiebuhr suggested in #14.

What would the semantics be of that?
```
first.cjson:
{
  "foo": "bar"
}

second.cjson:
{
  "bar": "qux"
}

$ oconf first.cjson second.cjson
{
  "foo": "bar"
  "bar": "qux"
}
```

That scenario is straight forward. But what happens if first.cjson includes third.cjson that also defines a value for "bar"? I guess the question is; In which order should files included in the command line args be loaded, compared to the files included in one of those files?

**Comment by gustavnikolaj** [comment]
Given the following files:
```
first.cjson:
{
  "#include": "third.cjson",
  "foo": "bar"
}

second.cjson:
{
  "bar": "qux"
}

third.cjson:
{
  "bar": "baz"
}
```

What would you expect the following invocation to output?
```
$ oconf first.cjson second.cjson
```

If we resolve each file independently and then merge them extend them backwards we would get:
```json
{
  "foo": "bar"
  "bar": "qux"
}
```

As first.cjson is resolved to the value `"baz"` at the key `bar` and then extended by second.cjson that would then overwrite the value to `"qux"`.

That is the easiest solution, both to implemenent, understand and communicate. But is it what you want to happen?

I don't really have a use case for this myself, so I'd need your feedback on this @msiebuhr.

**Comment by msiebuhr** [comment]
Admittedly, I haven't really had the need either, but here's my take;

    $ oconf 1.cjson 2.cjson 3.cjson

is equivalent to loading a single file with:

    { "#include": ["1.cjson", "2.cjson", "3.cjson"] }

**Comment by gustavnikolaj** [comment]
That seems in line with what I am suggesting above, although your explanation is a thousand times simpler :-)

**Comment by gustavnikolaj** [comment]
I've done some hacking around to take a stab at this, plus some other features that I have in mind, that requires a bit more advanced internals any way.

I've found a potential problem for the course of action that we have agreed on here.

What would happen in the following case:

```
first.cjson:
[1,2,3]

second.cjson:
[2,3,4]

$ oconf first.cjson second.cjson
```

I do not see the use case for a root level list in oconf, but we have a test that makes sure that it works.

I guess that the expected behaviour would be concatting them, so that you would get: `[1,2,3,2,3,4]`...?

**Comment by mwoc** [comment]
Without having seen this issue, I just landed this commit on a feature branch, which touches upon it:

https://github.com/One-com/node-oconf/commit/ff164c8ddea28ca51bfd01a06a98f2fb48d0be60

It may be doing the opposite of what's suggested here though.. 
Have ported it from another config loader which is mounted on top of oconf in our stack.

**Comment by gustavnikolaj** [comment]
So passing the entire array here, instead of the first item, would fix this: https://github.com/One-com/node-oconf/blob/master/bin/oconf#L106

What was the relevance of that addition to the feature branch?

**Comment by mwoc** [comment]
@gustavnikolaj Looks like it yes.

The only relevance with that feature branch is that I wanted to make sure with a unit test that it does the right thing when used like this, also with regards to the new `#public` behaviour (which it does).

**Comment by mwoc** [comment]
@gustavnikolaj could you review the mentioned commit ^?

**Comment by mwoc** [comment]
Closed via 40b8df27b2fa43188ca57657119593995112f406

**Comment by gustavnikolaj** [comment]
@mwoc If you make it a major version bump: LGTM

**Comment by gustavnikolaj** [comment]
Just noticed that you did... :-)

**Comment by mwoc** [comment]
:) yep
