### ISSUE TITLE
Reconsolidate the exported cli commands.

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/node-oconf#22]
I had a talk with @papandreou the other day, about the changes in the recent oconf version. We ended up agreeing that this might not have been the right decision. The current interface is quite rough, where the old one was a lot more fluent. I have the following idea of how to solve the muddied interface of the old singular binary without splitting it up. Before landing it, and making another massive API change, I'd like your feedback.

There will only be one exported cli command: `oconf`.

In it's simplest form, `oconf` is called with a path to a config file.

```
$ oconf file.cjson

file.cjson:
{
  "foo": "bar"
}
```

Other functionality is implemented through the use of flags. The `--lint` flag is a boolean that will exit with status code 0 if it was a valid file, and exit with status code 1 and an error message writtten to stderr if it was not.

```
$ oconf --lint file.cjson
```

The extract option functionality is likewise linting made into a flag, instead of relying on a positional argument as before (opening the possibility to solve #19 without a standalone command).
```
$ oconf file.cjson --extract-option foo
bar
```

This leaves the question of how to handle the extra flags for `--extract-option`. Specifically the current `oconf-extract-option` flags `--allow-missing` and `--json`. `--allow-missing` will exit with status code 0 even if the value that you asked for was not present. `--json` will output the option in JSON.stringified format. These flags are harder, because they are subflags for another flag.

My best idea at the moment is to document that these flags are only working in the context of other flags, and name them such that it is more obvious.

```
$ oconf --allow-missing-option file.cjson
Error: The option --allow-missing-option only works when using the --extract-option feature.
```

```
$ oconf
Usage: oconf [--lint|--extract-option <option> [--allow-missing-option][--option-as-json]] <file>
```

The motivation for this change is that I feel this API, as described in the example above, is a lot simpler and clear enough that the separate commands are not warranted. I found myself force installing older versions of oconf, because using the new commands felt clunky, compared to the old API. 

ping @msiebuhr @papandreou

**Comment by msiebuhr** [comment]
What about some mode-thingie like ex `git` has, ex. `oconf lint <filename>`, `oconf json <filename>`...?

**Comment by gustavnikolaj** [comment]
A command pattern? Like `git` and `npm`... I think the yargs module actually includes that.

That solves the flags for flags problem. I guess that would be okay too. I still think I prefer having the flags.

The basic functionality of oconf is the same - nomatter which command you need. It will take the given input file (or files) and resolve them. If you don't pass any flags, it will just output the result - if you pass `--lint` it will only ouput a potential error - and if you pass `--extract` you will get whatever property you asked for...

While `--extract` has the need for extra flags, it also needs all the flags that the default oconf functionality provides. Like --ignore "glob pattern" to ignore a set of included files. Having flags that span multiple commands are at least as confusing as having flags that only works for some commands, in my opinion.

**Comment by gustavnikolaj** [comment]
s/flags that only works for some commands/flags that only works with some flags/

**Comment by gustavnikolaj** [comment]
First take at this effort: https://github.com/One-com/node-oconf/commit/ce40d11e95636e72ade2a9ea1af23b5c85d97883

This is just merging the three back together into one.

Things left to do:

- [ ] Test that ignore flag works across the different options
- [ ] Optimize code, and deduplicate it, if necessary
- [ ] Introduce old flags as aliases for the new, more verbose flags
- [ ] Introduce helpful error messages for common errors, like not providing `--extract-option` when extracting values.

**Comment by gustavnikolaj** [comment]
You can follow the work on this at: https://github.com/One-com/node-oconf/tree/feature/reconsolidate

I just folded the new unified oconf binary into the main one. And I replaced the two extra ones with hollow bash wrappers, mapping the input to the new oconf.

Code got really simple.

**Comment by gustavnikolaj** [comment]
- [ ] write readme
- [ ] handle missing --extract-option parameter.

**Comment by gustavnikolaj** [comment]
I released v4 (https://github.com/One-com/node-oconf/commit/091e0dbce44fdffec3fddeebe03b397cd8e9c73f) with the new options in it.
