### ISSUE TITLE
Support #public

### ISSUE THREAD

**Issue by mwoc** [One-com/node-oconf#25]
`{
   "someService": {
      "secret": "hulahuuu",
      "#public": {
           "url": "https://foo.bar.com/"
      }
   },
   "otherService": {
      "url": "http://foo.bar/"
   }
}`

oconf should preprocess the config file so the above snippet by default turns into this:

`{
   "someService": {
      "secret": "hulahuuu",
      "url": "https://foo.bar.com/"
   },
   "otherService": {
      "url": "http://foo.bar/"
   }
}`

But can also process into this when asking for a public version of the config, containing only the leaves and keys/values that are to be public.

`{
   "someService": {
      "url": "https://foo.bar.com/"
   }
}`

**Comment by mwoc** [comment]
Working on this in https://github.com/One-com/node-oconf/tree/feature/public - but I might have to change strategy a bit tomorrow.

**Comment by msiebuhr** [comment]
IMHO, I think pre/suffixing the keys, ex. `url#public`, would be a much saner interface. In particular, the structure of the final document would have some actual resemblance to the initial file. I can imagine some cases where promoting child-keys to be parents would be confusing (incesteous too!).

 * Are there ditto `#secret` functionality?
 * Who wins in case of conflict? Ex. `{ foo: 123, #secret: { foo: 321 } }`?

**Comment by mwoc** [comment]
Suffixing the keys would be an option too indeed, but if you have several keys on the same object that need to be public, they can be grouped if it's done like proposed. Also, it follows the semantics of `#include` - both `#include` and `#public` put the config values being included onto the object from where they're included.
Can you think of cases where that wouldn't work - i.e. where promoting child-keys to be parents would be confusing?

In the case of conflicts, an error is thrown. @papandreou and me were figuring that if the same key is used for both a public and a non-public config value, the end result is unpredictable (the client code might get a different value than the server code), so probably the user should introduce a new key instead.

There's no `#secret` behaviour, all non-public keys are implicitly secret already. Do you have a use case where an explicit `#secret` would give value?

@papandreou suggested furthermore to make all `#public` keys available in two ways in the server code, both by merging them into the normal config structure as shown above, and on a key on the root of the outputted config, also called `#public`. That would make it possible to load the config once for server and client code, and only expose the new `#public` blob to the frontend (otherwise the server handler exposing the public configuration to the frontend needs to know which config file was included to start with). I haven't yet gotten to that, but looking at our stack it seems to be the easiest way to implement this functionality. @msiebuhr do you have any ideas in this respect?

**Comment by mwoc** [comment]
Closed via https://github.com/One-com/node-oconf/commit/40b8df27b2fa43188ca57657119593995112f406

**Comment by papandreou** [comment]
After going through a bunch of projects and adopting the `"#public": { ... }` syntax I actually agree with @msiebuhr that suffixing key names with `#public` would be easier to manage.
