### ISSUE TITLE
Publish 5.3.0 to npm

### ISSUE THREAD

**Issue by rolandliwag** [One-com/node-oconf#32]
I bumped the version to 5.3.0 since support for older node versions is being dropped. But I don't have npm publish permission for this package.

**Comment by papandreou** [comment]
Looks like I still have npm publish permissions, I published 5.3.0 now :hugs:

**Comment by msiebuhr** [comment]
Actually, I have ownership of quite a few packages back from the One.com days (and I don't really work on those any more).

Wouldn't it make sense to re-assign the NPM rights to those?
