### ISSUE TITLE
NPM Dependency package optimist is deprecated

### ISSUE THREAD

**Issue by Swanoff** [One-com/node-oconf#35]
The npm package [optimist](https://www.npmjs.com/package/optimist) is deprecated.
Also this package uses a version of minimist which has critical vulnerability as per `npm audit`

The optimist package author recommends to use [yargs](https://www.npmjs.com/package/yargs) instead.

**Comment by abhi11210646** [comment]
#36

**Comment by paras20xx** [comment]
Marking closed.
