### ISSUE TITLE
Test behavior of recursive merging

### ISSUE THREAD

**Issue by msiebuhr** [One-com/node-oconf#6]
When merging data recursively using `#includes` - test that it actually behaves as expected.

**Comment by gustavnikolaj** [comment]
@msiebuhr Do you remember what the bug was?

Is it testing that, given the following three files, you get the following output?

file1.json
```json
{
  "#include": "file2.json",
  "foo": "foo"
}
```

file2.json
```json
{
  "#include": "file3.json",
  "foo": "bar",
  "bar": "bar",
}
```

file3.json
```json
{
  "foo": "baz",
  "bar": "baz",
  "baz": "baz"
}
```

output
```json
{
  "foo": "foo",
  "bar": "bar",
  "baz": "baz"
}
```

**Comment by msiebuhr** [comment]
That looks right - I just don't believe we had a test for that back then :)

**Comment by gustavnikolaj** [comment]
The closest we have at the moment is: 
https://github.com/One-com/node-oconf/blob/master/test/index.js#L55

Where a test is made of including two files into the same master file.

I'll add a test of this.

**Comment by gustavnikolaj** [comment]
Ported the above examples to a test case and landed that.
